Fix git-squash-merge bug and better commit msg

diff --git a/git-squash-merge b/git-squash-merge
--- a/git-squash-merge
+++ b/git-squash-merge
@@ -35,6 +35,7 @@ then
 fi
 
 onto=$1
+onto_sha=$(git rev-parse "$onto")
 
 HEAD1=$(git rev-parse HEAD^1)
 HEAD2=$(git rev-parse HEAD^2)
@@ -53,6 +54,23 @@ if git rev-parse HEAD^3 >& /dev/null; then
     exit 1
 fi
 
+if [ "$onto_sha" = "$HEAD1" ]; then
+    echo
+    echo "ERROR: '$onto' already (first) parent of HEAD."
+    echo "       No commits to squash."
+    echo
+    exit 1
+fi
+if [ "$onto_sha" = "$HEAD2" ]; then
+    echo
+    echo "ERROR: '$onto' already (second) parent of HEAD."
+    echo "       No commits to squash."
+    echo
+    exit 1
+fi
+
+HEAD_MSG=$(git log -1 --format="%B" HEAD)
+
 if git merge-base --is-ancestor $onto $HEAD1; then
     if git merge-base --is-ancestor $onto $HEAD2; then
         echo
@@ -62,17 +80,21 @@ if git merge-base --is-ancestor $onto $HEAD1; then
 	exit 1
     fi
 
+    SQUASH_LOG=$(git log --format="%n%H %an%n%B" --ancestry-path $onto..$HEAD1)
+
     #git-create-merge $onto $HEAD2
     run git reset --soft $onto
     run git update-ref MERGE_HEAD $HEAD2
-    run git commit --reedit-message=$HEAD1
+    git commit --edit -m "$HEAD_MSG" -m "SQUASHED commits:" -m "$SQUASH_LOG"
 
 elif git merge-base --is-ancestor $onto $HEAD2; then
 
-    #git-create-merge $onto $HEAD1
-    run git reset --soft $onto
-    run git update-ref MERGE_HEAD $HEAD1
-    run git commit --reedit-message=$HEAD2
+    SQUASH_LOG=$(git log --format="%n%H %an%n%B" --ancestry-path $onto..$HEAD2)
+
+    #git-create-merge $HEAD1 $onto
+    run git reset --soft $HEAD1
+    run git update-ref MERGE_HEAD $onto
+    git commit --edit -m "$HEAD_MSG" -m "SQUASHED commits:" -m "$SQUASH_LOG"
 else
     echo
     echo "ERROR: '$onto' is not reachable from either HEAD^1 or HEAD^2."
